"""AI Proof-of-Risk domain enumerations.

Explicit domain states for routing decisions, scenario types, graph node/edge
categories, and redaction outcomes. No string comparisons outside this file.
"""

from enum import StrEnum


class AIRoute(StrEnum):
    """Token-efficient routing destination for AI analysis.

    ``rule_only`` handles simple, well-known findings with deterministic rules.
    ``local_amd_model`` targets medium-complexity classification on an AMD/ROCm
    local GPU. ``fireworks_gemma`` targets complex reasoning via Fireworks-hosted
    Gemma. ``deterministic_fallback`` is used when no provider is available.
    """

    rule_only = "rule_only"
    local_amd_model = "local_amd_model"
    fireworks_gemma = "fireworks_gemma"
    deterministic_fallback = "deterministic_fallback"


class FindingComplexity(StrEnum):
    """Complexity classification driving route selection."""

    simple = "simple"
    medium = "medium"
    complex = "complex"


class GraphNodeKind(StrEnum):
    """Kinds of nodes in the attack-surface graph."""

    asset = "asset"
    finding = "finding"
    missing_control = "missing_control"
    prerequisite = "prerequisite"
    potential_impact = "potential_impact"
    business_risk = "business_risk"
    remediation = "remediation"


class GraphEdgeKind(StrEnum):
    """Relationships between attack-surface graph nodes."""

    contributes_to = "contributes_to"
    requires = "requires"
    mitigated_by = "mitigated_by"
    simulated_by = "simulated_by"


class ScenarioType(StrEnum):
    """Supported digital-twin scenario categories."""

    missing_csp_browser_risk = "missing_csp_browser_risk"
    missing_x_frame_options_clickjacking = "missing_x_frame_options_clickjacking"
    insecure_cookie_flag_risk = "insecure_cookie_flag_risk"
    permissive_cors_simulation = "permissive_cors_simulation"
    generic_security_header_risk = "generic_security_header_risk"


class ExploitSimulationType(StrEnum):
    """How the scenario exercises the vulnerability in the sandbox.

    These are plan-only descriptors; no execution is performed in Step 1.
    """

    browser_xss_injection = "browser_xss_injection"
    clickjacking_frame_embed = "clickjacking_frame_embed"
    cookie_hijack_replay = "cookie_hijack_replay"
    cors_credential_theft = "cors_credential_theft"
    missing_security_header_simulation = "missing_security_header_simulation"


class RedactionCategory(StrEnum):
    """Categories of redacted material for the redaction summary."""

    authorization_header = "authorization_header"
    cookie_header = "cookie_header"
    set_cookie_header = "set_cookie_header"
    api_key = "api_key"
    bearer_token = "bearer_token"  # noqa: S105
    jwt_value = "jwt_value"
    private_key = "private_key"
    raw_request_body = "raw_request_body"
    raw_response_body = "raw_response_body"
    worker_credential_token = "worker_credential_token"  # noqa: S105
    broker_url = "broker_url"
    database_url = "database_url"
    kill_switch_token = "kill_switch_token"  # noqa: S105
    session_id = "session_id"
    opaque_secret = "opaque_secret"  # noqa: S105


class ProviderStatus(StrEnum):
    """Operational status of an AI provider."""

    available = "available"
    unavailable = "unavailable"
    degraded = "degraded"


class ProofType(StrEnum):
    """The type of proof generated by the sandbox simulation."""

    csp_sandbox_marker_execution = "csp_sandbox_marker_execution"
    clickjacking_frame_allowed = "clickjacking_frame_allowed"
    insecure_cookie_attribute_confirmed = "insecure_cookie_attribute_confirmed"
    permissive_cors_policy_confirmed = "permissive_cors_policy_confirmed"


class AnalysisMode(StrEnum):
    """The requested scope of the AI Proof-of-Risk analysis."""

    attack_surface_graph = "attack_surface_graph"
    exploitability_hypothesis = "exploitability_hypothesis"
    digital_twin_plan = "digital_twin_plan"
    sandbox_proof = "sandbox_proof"
    risk_tribunal = "risk_tribunal"
    remediation_plan = "remediation_plan"
    retest_plan = "retest_plan"
    full_report = "full_report"


class Audience(StrEnum):
    """The target audience for the generated report."""

    executive = "executive"
    security_engineer = "security_engineer"
    developer = "developer"
    auditor = "auditor"
