import type {
  Asset,
  AssetVerificationAttempt,
  AuditEvent,
  Authorization,
  CredentialRecord,
  DispatchWorkerState,
  DispatchQueueState,
  Engagement,
  ExecutionEvent,
  ExecutionStepResult,
  Organization,
  Project,
  ValidationExecution,
} from "./types";

// ============================================================
// SecureScope — Mock Domain Data
// Realistic enterprise cybersecurity content. No lorem ipsum.
// All sensitive values (raw tokens, broker URLs, raw credentials,
// response bodies, cookies, Authorization headers, Set-Cookie)
// are intentionally ABSENT from this dataset.
// ============================================================

export const ORG_NASARI = "org_nasari";
export const ORG_COREBANK = "org_corebank";
export const ORG_KDKMP = "org_kdkmp";

export const organizations: Organization[] = [
  {
    id: ORG_NASARI,
    name: "Nasari Security Lab",
    code: "NSL",
    status: "healthy",
    projectsCount: 4,
    verifiedAssets: 18,
    activeEngagements: 2,
    latestExecutionState: "succeeded",
    latestExecutionId: "EXEC-2026-0702-003",
    lastActivity: "2026-07-02T06:42:11Z",
  },
  {
    id: ORG_COREBANK,
    name: "Core Banking Validation",
    code: "CBV",
    status: "warning",
    projectsCount: 3,
    verifiedAssets: 11,
    activeEngagements: 1,
    latestExecutionState: "executing",
    latestExecutionId: "EXEC-2026-0702-002",
    lastActivity: "2026-07-02T07:01:54Z",
  },
  {
    id: ORG_KDKMP,
    name: "KDKMP Digital Platform",
    code: "KDKMP",
    status: "healthy",
    projectsCount: 2,
    verifiedAssets: 7,
    activeEngagements: 0,
    latestExecutionState: "queued",
    latestExecutionId: "EXEC-2026-0702-001",
    lastActivity: "2026-07-02T05:18:30Z",
  },
];

export const projects: Project[] = [
  {
    id: "prj_mobile_api",
    name: "Mobile API Security",
    code: "MOB-API",
    organizationId: ORG_NASARI,
    organizationName: "Nasari Security Lab",
    status: "healthy",
    assetsCount: 6,
    activeAuthorizations: 2,
    activeEngagements: 1,
    latestExecutionId: "EXEC-2026-0702-003",
    lastActivity: "2026-07-02T06:42:11Z",
  },
  {
    id: "prj_core_gateway",
    name: "Core Banking Gateway",
    code: "CB-GW",
    organizationId: ORG_COREBANK,
    organizationName: "Core Banking Validation",
    status: "warning",
    assetsCount: 4,
    activeAuthorizations: 1,
    activeEngagements: 1,
    latestExecutionId: "EXEC-2026-0702-002",
    lastActivity: "2026-07-02T07:01:54Z",
  },
  {
    id: "prj_admin_console",
    name: "Admin Console Validation",
    code: "ADM-CON",
    organizationId: ORG_KDKMP,
    organizationName: "KDKMP Digital Platform",
    status: "healthy",
    assetsCount: 3,
    activeAuthorizations: 1,
    activeEngagements: 0,
    latestExecutionId: "EXEC-2026-0702-001",
    lastActivity: "2026-07-02T05:18:30Z",
  },
];

export const assets: Asset[] = [
  {
    id: "ast_api_nasari",
    name: "Nasari Public API",
    type: "web_api",
    criticality: "high",
    target: "api.nasari.local",
    verification: "verified",
    ownershipVerified: true,
    organizationId: ORG_NASARI,
    organizationName: "Nasari Security Lab",
    projectId: "prj_mobile_api",
    projectName: "Mobile API Security",
    lastValidation: "2026-07-02T06:42:11Z",
    tags: ["production-mirror", "tls-strict", "scope:headers"],
  },
  {
    id: "ast_staging_mobile",
    name: "Staging Mobile API",
    type: "web_api",
    criticality: "medium",
    target: "staging-mobile-api.securescope.test",
    verification: "verified",
    ownershipVerified: true,
    organizationId: ORG_NASARI,
    organizationName: "Nasari Security Lab",
    projectId: "prj_mobile_api",
    projectName: "Mobile API Security",
    lastValidation: "2026-07-01T22:14:02Z",
    tags: ["staging", "scope:headers", "scope:tls"],
  },
  {
    id: "ast_admin_console",
    name: "Admin Console",
    type: "web_app",
    criticality: "critical",
    target: "admin-console.securescope.test",
    verification: "verified",
    ownershipVerified: true,
    organizationId: ORG_KDKMP,
    organizationName: "KDKMP Digital Platform",
    projectId: "prj_admin_console",
    projectName: "Admin Console Validation",
    lastValidation: "2026-07-02T05:18:30Z",
    tags: ["internal", "mfa-required", "scope:headers"],
  },
  {
    id: "ast_core_gw",
    name: "Core Banking Gateway",
    type: "web_api",
    criticality: "critical",
    target: "core-gw.bank-mirror.local",
    verification: "verified",
    ownershipVerified: true,
    organizationId: ORG_COREBANK,
    organizationName: "Core Banking Validation",
    projectId: "prj_core_gateway",
    projectName: "Core Banking Gateway",
    lastValidation: "2026-07-02T07:01:54Z",
    tags: ["production-mirror", "pci-scope", "scope:tls"],
  },
  {
    id: "ast_pending_dns",
    name: "Edge Auth Service",
    type: "web_api",
    criticality: "high",
    target: "edge-auth.nasari-sandbox.test",
    verification: "pending",
    ownershipVerified: false,
    organizationId: ORG_NASARI,
    organizationName: "Nasari Security Lab",
    projectId: "prj_mobile_api",
    projectName: "Mobile API Security",
    lastValidation: null,
    tags: ["sandbox", "scope:headers"],
  },
  {
    id: "ast_failed_dns",
    name: "Reporting Endpoint",
    type: "web_api",
    criticality: "medium",
    target: "reports.kdkmp-sandbox.test",
    verification: "failed",
    ownershipVerified: false,
    organizationId: ORG_KDKMP,
    organizationName: "KDKMP Digital Platform",
    projectId: "prj_admin_console",
    projectName: "Admin Console Validation",
    lastValidation: null,
    tags: ["sandbox"],
  },
];

export const verificationAttempts: AssetVerificationAttempt[] = [
  {
    id: "va_1",
    createdAt: "2026-07-02T05:18:30Z",
    state: "verified",
    method: "dns_txt",
    challengeHost: "_securescope-verify.api.nasari.local",
    durationMs: 4120,
    note: "TXT record matched issued challenge token.",
  },
  {
    id: "va_2",
    createdAt: "2026-07-01T18:44:11Z",
    state: "verified",
    method: "dns_txt",
    challengeHost: "_securescope-verify.staging-mobile-api.securescope.test",
    durationMs: 5230,
    note: "TXT record matched issued challenge token.",
  },
  {
    id: "va_3",
    createdAt: "2026-07-02T04:11:09Z",
    state: "pending",
    method: "dns_txt",
    challengeHost: "_securescope-verify.edge-auth.nasari-sandbox.test",
    durationMs: 0,
    note: "Awaiting operator DNS propagation. Challenge issued.",
  },
  {
    id: "va_4",
    createdAt: "2026-06-30T22:08:51Z",
    state: "failed",
    method: "dns_txt",
    challengeHost: "_securescope-verify.reports.kdkmp-sandbox.test",
    durationMs: 8800,
    note: "TXT record missing after 3 retries. Verify the zone and try again.",
  },
  {
    id: "va_5",
    createdAt: "2026-06-29T11:22:00Z",
    state: "expired",
    method: "dns_txt",
    challengeHost: "_securescope-verify.reports.kdkmp-sandbox.test",
    durationMs: 0,
    note: "Challenge TTL elapsed before verification.",
  },
];

export const authorizations: Authorization[] = [
  {
    id: "auth_001",
    code: "AUTH-NSL-001",
    organizationId: ORG_NASARI,
    organizationName: "Nasari Security Lab",
    projectId: "prj_mobile_api",
    projectName: "Mobile API Security",
    state: "active",
    validFrom: "2026-07-01T00:00:00Z",
    validUntil: "2026-07-15T23:59:59Z",
    maxRiskTier: "high",
    scopedAssets: ["ast_api_nasari", "ast_staging_mobile"],
    scopedAssetNames: ["Nasari Public API", "Staging Mobile API"],
    scope: {
      allowedPaths: ["/api/v1/*", "/api/v2/*", "/healthz"],
      excludedPaths: ["/api/v1/payments/*", "/api/v1/admin/*"],
      allowedPorts: [443],
      allowedHosts: ["api.nasari.local", "staging-mobile-api.securescope.test"],
    },
    supportingDoc: {
      name: "NSL-Auth-Pkg-2026-07.pdf",
      hash: "sha256:9f2a…b71c",
      signedBy: "k.andrade@nasari.sec",
      signedAt: "2026-06-30T14:22:00Z",
    },
    approvalTimeline: [
      { at: "2026-06-28T09:11:00Z", actor: "k.andrade@nasari.sec", action: "requested" },
      { at: "2026-06-29T11:30:00Z", actor: "iso@nasari.sec", action: "reviewed" },
      { at: "2026-06-30T14:22:00Z", actor: "k.andrade@nasari.sec", action: "signed" },
      { at: "2026-07-01T00:00:00Z", actor: "system:scheduler", action: "activated" },
    ],
    immutableLock: true,
  },
  {
    id: "auth_002",
    code: "AUTH-CBV-001",
    organizationId: ORG_COREBANK,
    organizationName: "Core Banking Validation",
    projectId: "prj_core_gateway",
    projectName: "Core Banking Gateway",
    state: "active",
    validFrom: "2026-07-01T00:00:00Z",
    validUntil: "2026-07-05T23:59:59Z",
    maxRiskTier: "moderate",
    scopedAssets: ["ast_core_gw"],
    scopedAssetNames: ["Core Banking Gateway"],
    scope: {
      allowedPaths: ["/gateway/v1/*", "/gateway/v1/health"],
      excludedPaths: ["/gateway/v1/transfer/*", "/gateway/v1/auth/*"],
      allowedPorts: [443],
      allowedHosts: ["core-gw.bank-mirror.local"],
    },
    supportingDoc: {
      name: "CBV-Auth-Pkg-2026-07.pdf",
      hash: "sha256:3c81…f29a",
      signedBy: "r.varga@cbv.sec",
      signedAt: "2026-06-30T16:01:00Z",
    },
    approvalTimeline: [
      { at: "2026-06-27T10:00:00Z", actor: "r.varga@cbv.sec", action: "requested" },
      { at: "2026-06-28T15:45:00Z", actor: "ciso@cbv.sec", action: "reviewed" },
      { at: "2026-06-30T16:01:00Z", actor: "r.varga@cbv.sec", action: "signed" },
      { at: "2026-07-01T00:00:00Z", actor: "system:scheduler", action: "activated" },
    ],
    immutableLock: true,
  },
  {
    id: "auth_003",
    code: "AUTH-KDKMP-001",
    organizationId: ORG_KDKMP,
    organizationName: "KDKMP Digital Platform",
    projectId: "prj_admin_console",
    projectName: "Admin Console Validation",
    state: "active",
    validFrom: "2026-07-01T00:00:00Z",
    validUntil: "2026-07-31T23:59:59Z",
    maxRiskTier: "high",
    scopedAssets: ["ast_admin_console"],
    scopedAssetNames: ["Admin Console"],
    scope: {
      allowedPaths: ["/admin/*", "/admin/healthz"],
      excludedPaths: ["/admin/users/delete/*", "/admin/billing/*"],
      allowedPorts: [443],
      allowedHosts: ["admin-console.securescope.test"],
    },
    supportingDoc: {
      name: "KDKMP-Auth-Pkg-2026-07.pdf",
      hash: "sha256:5d12…aa90",
      signedBy: "t.olsen@kdkmp.sec",
      signedAt: "2026-06-30T18:33:00Z",
    },
    approvalTimeline: [
      { at: "2026-06-26T08:00:00Z", actor: "t.olsen@kdkmp.sec", action: "requested" },
      { at: "2026-06-27T13:15:00Z", actor: "iso@kdkmp.sec", action: "reviewed" },
      { at: "2026-06-30T18:33:00Z", actor: "t.olsen@kdkmp.sec", action: "signed" },
      { at: "2026-07-01T00:00:00Z", actor: "system:scheduler", action: "activated" },
    ],
    immutableLock: true,
  },
  {
    id: "auth_004",
    code: "AUTH-NSL-002",
    organizationId: ORG_NASARI,
    organizationName: "Nasari Security Lab",
    projectId: "prj_mobile_api",
    projectName: "Mobile API Security",
    state: "draft",
    validFrom: "2026-07-10T00:00:00Z",
    validUntil: "2026-07-20T23:59:59Z",
    maxRiskTier: "moderate",
    scopedAssets: ["ast_staging_mobile"],
    scopedAssetNames: ["Staging Mobile API"],
    scope: {
      allowedPaths: ["/api/v2/*"],
      excludedPaths: ["/api/v2/admin/*"],
      allowedPorts: [443],
      allowedHosts: ["staging-mobile-api.securescope.test"],
    },
    supportingDoc: {
      name: "NSL-Auth-Pkg-2026-07-002.pdf",
      hash: "sha256:1f8c…77bd",
      signedBy: "—",
      signedAt: "—",
    },
    approvalTimeline: [
      { at: "2026-07-02T06:10:00Z", actor: "k.andrade@nasari.sec", action: "requested" },
    ],
    immutableLock: false,
  },
];

export const engagements: Engagement[] = [
  {
    id: "eng_001",
    code: "ENG-NSL-001",
    name: "Mobile API Header Hardening Sweep",
    organizationId: ORG_NASARI,
    organizationName: "Nasari Security Lab",
    projectId: "prj_mobile_api",
    projectName: "Mobile API Security",
    authorizationId: "auth_001",
    authorizationCode: "AUTH-NSL-001",
    state: "active",
    windowStart: "2026-07-02T05:00:00Z",
    windowEnd: "2026-07-02T09:00:00Z",
    maxRiskTier: "high",
    scopedAssetNames: ["Nasari Public API", "Staging Mobile API"],
    activeExecutions: 1,
    killSwitch: { state: "inactive" },
    createdAt: "2026-07-01T22:00:00Z",
  },
  {
    id: "eng_002",
    code: "ENG-CBV-001",
    name: "Core Gateway TLS Configuration Audit",
    organizationId: ORG_COREBANK,
    organizationName: "Core Banking Validation",
    projectId: "prj_core_gateway",
    projectName: "Core Banking Gateway",
    authorizationId: "auth_002",
    authorizationCode: "AUTH-CBV-001",
    state: "active",
    windowStart: "2026-07-02T06:00:00Z",
    windowEnd: "2026-07-02T10:00:00Z",
    maxRiskTier: "moderate",
    scopedAssetNames: ["Core Banking Gateway"],
    activeExecutions: 1,
    killSwitch: {
      state: "armed",
      activatedBy: "r.varga@cbv.sec",
      activatedAt: "2026-07-02T06:58:00Z",
      reason: "Operator staged manual hold pending ISO review of step 4 evidence.",
      affectedExecutions: ["EXEC-2026-0702-002"],
    },
    createdAt: "2026-07-01T23:30:00Z",
  },
  {
    id: "eng_003",
    code: "ENG-KDKMP-001",
    name: "Admin Console Security Header Validation",
    organizationId: ORG_KDKMP,
    organizationName: "KDKMP Digital Platform",
    projectId: "prj_admin_console",
    projectName: "Admin Console Validation",
    authorizationId: "auth_003",
    authorizationCode: "AUTH-KDKMP-001",
    state: "scheduled",
    windowStart: "2026-07-03T08:00:00Z",
    windowEnd: "2026-07-03T12:00:00Z",
    maxRiskTier: "high",
    scopedAssetNames: ["Admin Console"],
    activeExecutions: 0,
    killSwitch: { state: "inactive" },
    createdAt: "2026-07-01T20:00:00Z",
  },
  {
    id: "eng_004",
    code: "ENG-NSL-002",
    name: "Staging API Availability Probe (paused)",
    organizationId: ORG_NASARI,
    organizationName: "Nasari Security Lab",
    projectId: "prj_mobile_api",
    projectName: "Mobile API Security",
    authorizationId: "auth_001",
    authorizationCode: "AUTH-NSL-001",
    state: "paused",
    windowStart: "2026-07-01T22:00:00Z",
    windowEnd: "2026-07-02T02:00:00Z",
    maxRiskTier: "low",
    scopedAssetNames: ["Staging Mobile API"],
    activeExecutions: 0,
    killSwitch: { state: "inactive" },
    createdAt: "2026-07-01T18:00:00Z",
  },
];

// Helper to build safe credential records (no raw token ever)
function makeCredential(execId: string, orgId: string, active: boolean): CredentialRecord {
  const issuedAt = "2026-07-02T06:48:00Z";
  return {
    id: `cred_${execId.toLowerCase().replace(/-/g, "_")}`,
    organizationId: orgId,
    executionId: execId,
    allowedActions: ["scope:headers:read", "scope:tls:read", "scope:availability:probe"],
    issuedAt,
    expiresAt: active ? "2026-07-02T08:48:00Z" : "2026-07-02T07:12:00Z",
    revokedAt: active ? null : "2026-07-02T07:12:00Z",
    state: active ? "active" : "revoked",
    source: "per_execution",
    fallbackEnabled: false,
  };
}

function makeSteps(template: "headers" | "tls" | "availability", success: boolean) {
  if (template === "headers") {
    return [
      {
        id: "step_h_1",
        name: "Connect & TLS handshake",
        status: "succeeded" as const,
        durationMs: 312,
        evidencePreview: "TLS 1.3 negotiated · ALPN h2 · cert chain depth 2",
        safeSummary: "Handshake completed; session established.",
      },
      {
        id: "step_h_2",
        name: "Fetch baseline response",
        status: "succeeded" as const,
        durationMs: 188,
        evidencePreview: "HTTP/2 200 · 14 headers evaluated",
        safeSummary: "Baseline response captured for header analysis.",
      },
      {
        id: "step_h_3",
        name: "Strict-Transport-Security",
        status: success ? ("succeeded" as const) : ("failed" as const),
        durationMs: 12,
        evidencePreview: success
          ? "max-age=63072000; includeSubDomains; preload"
          : "missing",
        safeSummary: success
          ? "HSTS present with preload and includeSubDomains."
          : "HSTS header missing — recommend enabling with preload.",
      },
      {
        id: "step_h_4",
        name: "Content-Security-Policy",
        status: success ? ("succeeded" as const) : ("inconclusive" as const),
        durationMs: 9,
        evidencePreview: success
          ? "default-src 'self'; frame-ancestors 'none'"
          : "frame-ancestors not restricted",
        safeSummary: success
          ? "CSP restricts default source and frame ancestors."
          : "CSP present but frame-ancestors not constrained.",
      },
      {
        id: "step_h_5",
        name: "X-Content-Type-Options",
        status: "succeeded" as const,
        durationMs: 7,
        evidencePreview: "nosniff",
        safeSummary: "MIME sniffing disabled.",
      },
      {
        id: "step_h_6",
        name: "Referrer-Policy",
        status: success ? ("succeeded" as const) : ("failed" as const),
        durationMs: 8,
        evidencePreview: success ? "no-referrer" : "missing",
        safeSummary: success
          ? "Referrer leakage prevented."
          : "Referrer-Policy missing — may leak origin on outbound links.",
      },
    ];
  }
  if (template === "tls") {
    return [
      {
        id: "step_t_1",
        name: "Cipher suite enumeration",
        status: success ? "succeeded" : "inconclusive",
        durationMs: 540,
        evidencePreview: success
          ? "TLS_AES_256_GCM_SHA384 · TLS_CHACHA20_POLY1305_SHA256"
          : "1 weak cipher offered: TLS_RSA_WITH_3DES_EDE_CBC_SHA",
        safeSummary: success
          ? "Only AEAD ciphers negotiated."
          : "Weak cipher detected — recommend removal from configuration.",
      },
      {
        id: "step_t_2",
        name: "Protocol version check",
        status: "succeeded",
        durationMs: 210,
        evidencePreview: "TLS 1.3 only · TLS 1.2 disabled",
        safeSummary: "No legacy protocol versions offered.",
      },
      {
        id: "step_t_3",
        name: "Certificate chain depth",
        status: "succeeded",
        durationMs: 96,
        evidencePreview: "depth=2 · leaf → intermediate → root",
        safeSummary: "Chain complete and ordered.",
      },
    ];
  }
  return [
    {
      id: "step_a_1",
      name: "TCP reachability",
      status: "succeeded",
      durationMs: 42,
      evidencePreview: "443/tcp reachable from worker region eu-1",
      safeSummary: "Endpoint reachable from worker egress.",
    },
    {
      id: "step_a_2",
      name: "HTTP availability probe",
      status: success ? "succeeded" : "inconclusive",
      durationMs: 218,
      evidencePreview: success ? "5/5 probes 200 OK" : "3/5 probes 503",
      safeSummary: success
        ? "Availability within expected thresholds."
        : "Intermittent 503 — investigate upstream health.",
    },
  ];
}

function makeEvents(
  execId: string,
  kind: "running" | "succeeded" | "failed" | "blocked"
): ExecutionEvent[] {
  const base: ExecutionEvent[] = [
    {
      id: `ev_${execId}_1`,
      at: "2026-07-02T06:45:02Z",
      kind: "worker_started",
      label: "Worker started",
      safeMeta: { worker_id: "wkr-eu-1-a07", region: "eu-1", exec_id: execId },
    },
  ];
  if (kind === "running") return base;
  if (kind === "blocked") {
    return [
      ...base,
      {
        id: `ev_${execId}_2`,
        at: "2026-07-02T06:47:11Z",
        kind: "blocked_by_control",
        label: "Blocked by safety control",
        safeMeta: { control: "kill_switch", reason: "Operator armed kill switch on engagement", exec_id: execId },
      },
      {
        id: `ev_${execId}_3`,
        at: "2026-07-02T06:47:12Z",
        kind: "credential_revoked",
        label: "Credential revoked",
        safeMeta: { cred_id: `cred_${execId.toLowerCase().replace(/-/g, "_")}`, reason: "blocked_by_control" },
      },
    ];
  }
  if (kind === "failed") {
    return [
      ...base,
      {
        id: `ev_${execId}_2`,
        at: "2026-07-02T06:52:48Z",
        kind: "failed_safely",
        label: "Worker finished — failed safely",
        safeMeta: { outcome: "failed_safely", steps_failed: 2, exec_id: execId },
      },
      {
        id: `ev_${execId}_3`,
        at: "2026-07-02T06:52:49Z",
        kind: "worker_finished",
        label: "Worker finished",
        safeMeta: { worker_id: "wkr-eu-1-a07", region: "eu-1" },
      },
      {
        id: `ev_${execId}_4`,
        at: "2026-07-02T06:52:50Z",
        kind: "credential_revoked",
        label: "Credential revoked",
        safeMeta: { cred_id: `cred_${execId.toLowerCase().replace(/-/g, "_")}`, reason: "execution_finished" },
      },
    ];
  }
  // succeeded
  return [
    ...base,
    {
      id: `ev_${execId}_2`,
      at: "2026-07-02T06:48:11Z",
      kind: "worker_finished",
      label: "Worker finished",
      safeMeta: { worker_id: "wkr-eu-1-a07", region: "eu-1", steps_total: 6, steps_failed: 0 },
    },
    {
      id: `ev_${execId}_3`,
      at: "2026-07-02T06:48:12Z",
      kind: "credential_revoked",
      label: "Credential revoked",
      safeMeta: { cred_id: `cred_${execId.toLowerCase().replace(/-/g, "_")}`, reason: "execution_finished" },
    },
  ];
}

export const executions: ValidationExecution[] = [
  {
    id: "exec_002",
    code: "EXEC-2026-0702-002",
    status: "executing",
    outcome: null,
    organizationId: ORG_COREBANK,
    organizationName: "Core Banking Validation",
    projectId: "prj_core_gateway",
    projectName: "Core Banking Gateway",
    assetId: "ast_core_gw",
    assetName: "Core Banking Gateway",
    assetTargetMasked: "core-gw.bank-mirror.local",
    authorizationId: "auth_002",
    authorizationCode: "AUTH-CBV-001",
    engagementId: "eng_002",
    engagementCode: "ENG-CBV-001",
    templateId: "tpl_tls",
    templateName: "Safe TLS Configuration Check",
    riskTier: "moderate",
    queuedAt: "2026-07-02T06:44:55Z",
    dispatchingAt: "2026-07-02T06:45:00Z",
    workerStartedAt: "2026-07-02T06:45:02Z",
    workerFinishedAt: null,
    scopeSnapshot: {
      allowedPaths: ["/gateway/v1/*", "/gateway/v1/health"],
      excludedPaths: ["/gateway/v1/transfer/*", "/gateway/v1/auth/*"],
      allowedPorts: [443],
      maxRiskTier: "moderate",
      scopedAssets: ["Core Banking Gateway"],
    },
    safetySnapshot: {
      assetVerified: true,
      authorizationActive: true,
      engagementActive: true,
      scopeMatch: true,
      windowValid: true,
      killSwitchInactive: true,
      riskTierAllowed: true,
      credentialIssued: true,
      dispatchBackendAvailable: true,
      workerAuthModeReady: true,
    },
    steps: makeSteps("tls", false),
    events: makeEvents("EXEC-2026-0702-002", "running"),
    credential: makeCredential("EXEC-2026-0702-002", ORG_COREBANK, true),
    dispatchMessage: {
      messageId: "msg_8af2c1",
      queueName: "securescope.exec.v1",
      routingKey: "exec.eu-1.tls",
      envelopeSchemaVersion: "v1.4.0",
      payloadHash: "sha256:7c91…2bd4",
      publishStatus: "published",
      workerState: "running",
      lastHeartbeat: "2026-07-02T07:01:48Z",
    },
  },
  {
    id: "exec_003",
    code: "EXEC-2026-0702-003",
    status: "succeeded",
    outcome: "validated",
    organizationId: ORG_NASARI,
    organizationName: "Nasari Security Lab",
    projectId: "prj_mobile_api",
    projectName: "Mobile API Security",
    assetId: "ast_api_nasari",
    assetName: "Nasari Public API",
    assetTargetMasked: "api.nasari.local",
    authorizationId: "auth_001",
    authorizationCode: "AUTH-NSL-001",
    engagementId: "eng_001",
    engagementCode: "ENG-NSL-001",
    templateId: "tpl_headers",
    templateName: "HTTP Security Header Validation",
    riskTier: "high",
    queuedAt: "2026-07-02T06:40:12Z",
    dispatchingAt: "2026-07-02T06:40:18Z",
    workerStartedAt: "2026-07-02T06:40:20Z",
    workerFinishedAt: "2026-07-02T06:42:11Z",
    scopeSnapshot: {
      allowedPaths: ["/api/v1/*", "/api/v2/*", "/healthz"],
      excludedPaths: ["/api/v1/payments/*", "/api/v1/admin/*"],
      allowedPorts: [443],
      maxRiskTier: "high",
      scopedAssets: ["Nasari Public API", "Staging Mobile API"],
    },
    safetySnapshot: {
      assetVerified: true,
      authorizationActive: true,
      engagementActive: true,
      scopeMatch: true,
      windowValid: true,
      killSwitchInactive: true,
      riskTierAllowed: true,
      credentialIssued: true,
      dispatchBackendAvailable: true,
      workerAuthModeReady: true,
    },
    steps: makeSteps("headers", true),
    events: makeEvents("EXEC-2026-0702-003", "succeeded"),
    credential: makeCredential("EXEC-2026-0702-003", ORG_NASARI, false),
    dispatchMessage: {
      messageId: "msg_3d8e91",
      queueName: "securescope.exec.v1",
      routingKey: "exec.eu-1.headers",
      envelopeSchemaVersion: "v1.4.0",
      payloadHash: "sha256:1a55…9ce0",
      publishStatus: "published",
      workerState: "finished",
      lastHeartbeat: "2026-07-02T06:42:10Z",
    },
  },
  {
    id: "exec_001",
    code: "EXEC-2026-0702-001",
    status: "queued",
    outcome: null,
    organizationId: ORG_KDKMP,
    organizationName: "KDKMP Digital Platform",
    projectId: "prj_admin_console",
    projectName: "Admin Console Validation",
    assetId: "ast_admin_console",
    assetName: "Admin Console",
    assetTargetMasked: "admin-console.securescope.test",
    authorizationId: "auth_003",
    authorizationCode: "AUTH-KDKMP-001",
    engagementId: "eng_003",
    engagementCode: "ENG-KDKMP-001",
    templateId: "tpl_headers",
    templateName: "HTTP Security Header Validation",
    riskTier: "high",
    queuedAt: "2026-07-02T05:18:30Z",
    dispatchingAt: null,
    workerStartedAt: null,
    workerFinishedAt: null,
    scopeSnapshot: {
      allowedPaths: ["/admin/*", "/admin/healthz"],
      excludedPaths: ["/admin/users/delete/*", "/admin/billing/*"],
      allowedPorts: [443],
      maxRiskTier: "high",
      scopedAssets: ["Admin Console"],
    },
    safetySnapshot: {
      assetVerified: true,
      authorizationActive: true,
      engagementActive: false,
      scopeMatch: true,
      windowValid: false,
      killSwitchInactive: true,
      riskTierAllowed: true,
      credentialIssued: false,
      dispatchBackendAvailable: true,
      workerAuthModeReady: true,
    },
    steps: [],
    events: [],
    credential: makeCredential("EXEC-2026-0702-001", ORG_KDKMP, false),
    dispatchMessage: {
      messageId: "msg_pending_001",
      queueName: "securescope.exec.v1",
      routingKey: "exec.eu-1.headers",
      envelopeSchemaVersion: "v1.4.0",
      payloadHash: "sha256:pending",
      publishStatus: "pending",
      workerState: "idle",
      lastHeartbeat: "—",
    },
  },
  {
    id: "exec_prev_1",
    code: "EXEC-2026-0701-014",
    status: "failed",
    outcome: "failed_safely",
    organizationId: ORG_NASARI,
    organizationName: "Nasari Security Lab",
    projectId: "prj_mobile_api",
    projectName: "Mobile API Security",
    assetId: "ast_staging_mobile",
    assetName: "Staging Mobile API",
    assetTargetMasked: "staging-mobile-api.securescope.test",
    authorizationId: "auth_001",
    authorizationCode: "AUTH-NSL-001",
    engagementId: "eng_004",
    engagementCode: "ENG-NSL-002",
    templateId: "tpl_headers",
    templateName: "HTTP Security Header Validation",
    riskTier: "low",
    queuedAt: "2026-07-01T22:30:00Z",
    dispatchingAt: "2026-07-01T22:30:08Z",
    workerStartedAt: "2026-07-01T22:30:11Z",
    workerFinishedAt: "2026-07-01T22:32:48Z",
    scopeSnapshot: {
      allowedPaths: ["/api/v2/*"],
      excludedPaths: ["/api/v2/admin/*"],
      allowedPorts: [443],
      maxRiskTier: "low",
      scopedAssets: ["Staging Mobile API"],
    },
    safetySnapshot: {
      assetVerified: true,
      authorizationActive: true,
      engagementActive: true,
      scopeMatch: true,
      windowValid: true,
      killSwitchInactive: true,
      riskTierAllowed: true,
      credentialIssued: true,
      dispatchBackendAvailable: true,
      workerAuthModeReady: true,
    },
    steps: makeSteps("headers", false),
    events: makeEvents("EXEC-2026-0701-014", "failed"),
    credential: makeCredential("EXEC-2026-0701-014", ORG_NASARI, false),
    dispatchMessage: {
      messageId: "msg_2b7f00",
      queueName: "securescope.exec.v1",
      routingKey: "exec.eu-1.headers",
      envelopeSchemaVersion: "v1.4.0",
      payloadHash: "sha256:b81f…44ac",
      publishStatus: "published",
      workerState: "finished",
      lastHeartbeat: "2026-07-01T22:32:47Z",
    },
  },
  {
    id: "exec_prev_2",
    code: "EXEC-2026-0701-009",
    status: "blocked",
    outcome: "blocked_by_control",
    organizationId: ORG_NASARI,
    organizationName: "Nasari Security Lab",
    projectId: "prj_mobile_api",
    projectName: "Mobile API Security",
    assetId: "ast_staging_mobile",
    assetName: "Staging Mobile API",
    assetTargetMasked: "staging-mobile-api.securescope.test",
    authorizationId: "auth_001",
    authorizationCode: "AUTH-NSL-001",
    engagementId: "eng_004",
    engagementCode: "ENG-NSL-002",
    templateId: "tpl_availability",
    templateName: "API Availability Safety Check",
    riskTier: "low",
    queuedAt: "2026-07-01T20:14:00Z",
    dispatchingAt: "2026-07-01T20:14:08Z",
    workerStartedAt: "2026-07-01T20:14:11Z",
    workerFinishedAt: null,
    scopeSnapshot: {
      allowedPaths: ["/api/v2/*"],
      excludedPaths: ["/api/v2/admin/*"],
      allowedPorts: [443],
      maxRiskTier: "low",
      scopedAssets: ["Staging Mobile API"],
    },
    safetySnapshot: {
      assetVerified: true,
      authorizationActive: true,
      engagementActive: true,
      scopeMatch: true,
      windowValid: true,
      killSwitchInactive: false,
      riskTierAllowed: true,
      credentialIssued: true,
      dispatchBackendAvailable: true,
      workerAuthModeReady: true,
    },
    steps: [],
    events: makeEvents("EXEC-2026-0701-009", "blocked"),
    credential: makeCredential("EXEC-2026-0701-009", ORG_NASARI, false),
    dispatchMessage: {
      messageId: "msg_9c4d11",
      queueName: "securescope.exec.v1",
      routingKey: "exec.eu-1.availability",
      envelopeSchemaVersion: "v1.4.0",
      payloadHash: "sha256:6e22…0f8a",
      publishStatus: "published",
      workerState: "error",
      lastHeartbeat: "2026-07-01T20:47:13Z",
    },
  },
];

export const dispatchQueues: DispatchQueueState[] = [
  {
    queueName: "securescope.exec.v1",
    routingKey: "exec.eu-1.#",
    pending: 1,
    active: 1,
    failed: 0,
    brokerStatus: "online",
  },
  {
    queueName: "securescope.exec.v1",
    routingKey: "exec.us-1.#",
    pending: 0,
    active: 0,
    failed: 0,
    brokerStatus: "online",
  },
  {
    queueName: "securescope.deadletter.v1",
    routingKey: "deadletter.#",
    pending: 0,
    active: 0,
    failed: 1,
    brokerStatus: "online",
  },
];

export const workers: DispatchWorkerState[] = [
  {
    workerId: "wkr-eu-1-a07",
    state: "running",
    lastHeartbeat: "2026-07-02T07:01:48Z",
    currentExecutionId: "EXEC-2026-0702-002",
    region: "eu-1",
  },
  {
    workerId: "wkr-eu-1-b02",
    state: "idle",
    lastHeartbeat: "2026-07-02T07:01:50Z",
    currentExecutionId: null,
    region: "eu-1",
  },
  {
    workerId: "wkr-us-1-c11",
    state: "offline",
    lastHeartbeat: "2026-07-02T05:12:00Z",
    currentExecutionId: null,
    region: "us-1",
  },
  {
    workerId: "wkr-eu-1-d05",
    state: "finished",
    lastHeartbeat: "2026-07-02T06:42:10Z",
    currentExecutionId: null,
    region: "eu-1",
  },
];

export const auditEvents: AuditEvent[] = [
  {
    id: "aud_1",
    at: "2026-07-02T07:01:48Z",
    actor: "system:dispatch",
    actorType: "system",
    action: "worker.heartbeat",
    entityType: "dispatch",
    entityId: "wkr-eu-1-a07",
    executionId: "EXEC-2026-0702-002",
    safeMetadata: { region: "eu-1", worker_state: "running" },
  },
  {
    id: "aud_2",
    at: "2026-07-02T06:58:00Z",
    actor: "r.varga@cbv.sec",
    actorType: "operator",
    action: "engagement.kill_switch.armed",
    entityType: "engagement",
    entityId: "ENG-CBV-001",
    organizationId: ORG_COREBANK,
    projectId: "prj_core_gateway",
    executionId: "EXEC-2026-0702-002",
    safeMetadata: {
      reason: "Operator staged manual hold pending ISO review of step 4 evidence.",
      affected_executions: "EXEC-2026-0702-002",
    },
  },
  {
    id: "aud_3",
    at: "2026-07-02T06:45:02Z",
    actor: "system:scheduler",
    actorType: "scheduler",
    action: "execution.worker.started",
    entityType: "execution",
    entityId: "EXEC-2026-0702-002",
    organizationId: ORG_COREBANK,
    projectId: "prj_core_gateway",
    executionId: "EXEC-2026-0702-002",
    safeMetadata: { worker_id: "wkr-eu-1-a07", region: "eu-1" },
  },
  {
    id: "aud_4",
    at: "2026-07-02T06:44:55Z",
    actor: "k.andrade@nasari.sec",
    actorType: "operator",
    action: "execution.queued",
    entityType: "execution",
    entityId: "EXEC-2026-0702-002",
    organizationId: ORG_COREBANK,
    projectId: "prj_core_gateway",
    executionId: "EXEC-2026-0702-002",
    safeMetadata: {
      template: "Safe TLS Configuration Check",
      risk_tier: "moderate",
      credential_source: "per_execution",
    },
  },
  {
    id: "aud_5",
    at: "2026-07-02T06:42:11Z",
    actor: "system:worker",
    actorType: "worker",
    action: "execution.finished",
    entityType: "execution",
    entityId: "EXEC-2026-0702-003",
    organizationId: ORG_NASARI,
    projectId: "prj_mobile_api",
    executionId: "EXEC-2026-0702-003",
    safeMetadata: { outcome: "validated", steps_total: "6", steps_failed: "0" },
  },
  {
    id: "aud_6",
    at: "2026-07-02T06:42:12Z",
    actor: "system:credential",
    actorType: "system",
    action: "credential.revoked",
    entityType: "credential",
    entityId: "cred_exec_2026_0702_003",
    organizationId: ORG_NASARI,
    executionId: "EXEC-2026-0702-003",
    safeMetadata: { reason: "execution_finished" },
  },
  {
    id: "aud_7",
    at: "2026-07-02T06:10:00Z",
    actor: "k.andrade@nasari.sec",
    actorType: "operator",
    action: "authorization.draft.created",
    entityType: "authorization",
    entityId: "AUTH-NSL-002",
    organizationId: ORG_NASARI,
    projectId: "prj_mobile_api",
    safeMetadata: { max_risk_tier: "moderate", scoped_assets: "1" },
  },
  {
    id: "aud_8",
    at: "2026-07-02T05:18:30Z",
    actor: "t.olsen@kdkmp.sec",
    actorType: "operator",
    action: "execution.queued",
    entityType: "execution",
    entityId: "EXEC-2026-0702-001",
    organizationId: ORG_KDKMP,
    projectId: "prj_admin_console",
    executionId: "EXEC-2026-0702-001",
    safeMetadata: {
      template: "HTTP Security Header Validation",
      risk_tier: "high",
      engagement_state: "scheduled",
    },
  },
  {
    id: "aud_9",
    at: "2026-07-02T04:11:09Z",
    actor: "system:scheduler",
    actorType: "scheduler",
    action: "asset.verification.challenge_issued",
    entityType: "asset",
    entityId: "ast_pending_dns",
    organizationId: ORG_NASARI,
    projectId: "prj_mobile_api",
    assetId: "ast_pending_dns",
    safeMetadata: { method: "dns_txt", challenge_host: "_securescope-verify.edge-auth.nasari-sandbox.test" },
  },
  {
    id: "aud_10",
    at: "2026-07-01T23:30:00Z",
    actor: "r.varga@cbv.sec",
    actorType: "operator",
    action: "engagement.activated",
    entityType: "engagement",
    entityId: "ENG-CBV-001",
    organizationId: ORG_COREBANK,
    projectId: "prj_core_gateway",
    safeMetadata: { window_start: "2026-07-02T06:00:00Z", max_risk_tier: "moderate" },
  },
  {
    id: "aud_11",
    at: "2026-07-01T22:00:00Z",
    actor: "k.andrade@nasari.sec",
    actorType: "operator",
    action: "engagement.created",
    entityType: "engagement",
    entityId: "ENG-NSL-001",
    organizationId: ORG_NASARI,
    projectId: "prj_mobile_api",
    safeMetadata: { authorization: "AUTH-NSL-001", max_risk_tier: "high" },
  },
  {
    id: "aud_12",
    at: "2026-07-01T00:00:00Z",
    actor: "system:scheduler",
    actorType: "scheduler",
    action: "authorization.activated",
    entityType: "authorization",
    entityId: "AUTH-NSL-001",
    organizationId: ORG_NASARI,
    safeMetadata: { valid_until: "2026-07-15T23:59:59Z" },
  },
];

// Active execution focus for the dashboard
export const activeExecutionFocus = executions.find((e) => e.status === "executing")!;

export const templates = [
  {
    id: "tpl_headers",
    name: "HTTP Security Header Validation",
    description: "Evaluates HSTS, CSP, X-Content-Type-Options, Referrer-Policy and related headers against baseline.",
    steps: 6,
    riskTier: "low" as const,
    estimatedSeconds: 120,
  },
  {
    id: "tpl_tls",
    name: "Safe TLS Configuration Check",
    description: "Inspects cipher suites, protocol versions and certificate chain depth without active exploitation.",
    steps: 3,
    riskTier: "moderate" as const,
    estimatedSeconds: 90,
  },
  {
    id: "tpl_availability",
    name: "API Availability Safety Check",
    description: "Performs bounded availability probing within authorized scope and rate limits.",
    steps: 2,
    riskTier: "low" as const,
    estimatedSeconds: 45,
  },
];
